language: python

sudo: false

addons:
  apt:
    packages:
    - python-lxml
    - python3-lxml

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
 - pip install -e .

script:
 - bot-test unity python integration
 - python tests/run.py